labels:
  - name: homework
    color: "#284A85"
    description: Homework problem that needs addressing
  - name: exercise
    color: "#3F9E78"
    description: Exercise left to the reader that should be done
  - name: proof
    color: "#1E4278"
    description: Proof that needs to be written or polished
  - name: style
    color: "#D9D186"
    description: Stylistic issues that do not affect correctness
  - name: error
    color: "#D90D0D"
    description: Error in mathematical reasoning that needs correction
  - name: citation
    color: "#542678"
    description: Citation or background research required

branches:
  - name: main
    protection:
      required_pull_request_reviews: null
      required_status_checks:
        strict: true
        contexts: []
      enforce_admins: true
      restrictions: null
