title: Course title
logo: /assets/img/logo.png
description: Description of the course
show_downloads: false
theme: jekyll-theme-minimal
github:
  is_project_page: false
  is_user_page: true
  owner_url: "https://github.com/qwinters"
