name: LaTeX lint with chtex
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: LaTeX linter (chktex)
        uses: j2kun/chktex-action@1.0.3
