name: Automatically assign issues to their creators
on:
  issues:
    types: [opened]
jobs:
  run:
    name: Automatically assign issues to their creators
    runs-on: ubuntu-latest
    steps:
      - uses: wow-actions/auto-assign@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CONFIG_FILE: .github/configs/auto-assign-config.yml

