name: Automatically create issues from TODO comments
on: ["push"]
jobs:
  build:
    name: Automatically create issues from TODO comments
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@master"
      - name: "TODO to Issue"
        uses: "alstr/todo-to-issue-action@v4.5"
        id: "todo"
        with:
          AUTO_ASSIGN: true
