name: Update lecture notes on website
on:
  push:
    branches: [main]
jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Copy lectures to gh-pages on main branch 
        id: git_copy_lectures
        shell: bash 
        run: |
            git config --local user.name "github-action"
            cp -r lectures/ gh-pages/_posts
            if [[ $(git status --porcelain | wc -l) -eq "0" ]] ; then 
              git add gh-pages/_posts
              git commit -m "chore(gh-pages): Updating posts"
              git push
            fi 
      - name: Deploy notes to github pages
        id: deploy_gh_pages
        if: success()
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with: 
          branch: website
          folder: gh-pages
